### ISSUE TITLE
NXBoot doesn't install properly under rootless jailbreaks.

### ISSUE THREAD

**Issue by afastaudir8** [mologie/nxboot#7]
Hello.
When attempting to install NXBoot under a rootless jailbreak (iOS 15.0) the package gets stuck at "Installed". If the install actually completes, the app icon doesn't appear anywhere even after running uicache.

**Comment by mologie** [comment]
Hi, thanks for the message. Could you provide /any/ information to help diagnose this beyond that it's a rootless jailbreak? I suspect this happens because the .deb file writes NXBoot.app to `/Applications`, and the rootless jailbreak does not account for .deb files that attempt to write to it since it's now read-only.

I do not have test devices with iOS 15 or a rootless jailbreak, so all I can act on is the info you give.

In no particular order:

* What is your phone model?
* What jailbreak do you use?
* Which installation application do you use?
* Can you access DPKG or installer logs and attach them?
* Can you download [com.mologie.NXBoot-0.1.1-5.deb](https://mologie.github.io/repo/com.mologie.NXBoot-0.1.1-5.deb) and run `dpkg -i <path-to-deb>` on it manually via SSH? What is the output?
